#!/usr/bin/env bash
# Mechanical rename LampaStream -> LampaStream for the LampaStream repository.
#
# What it does (idempotent on a clean tree):
#   1. git mv every tracked path containing "lampastream" / "LampaStream"
#      (src/lampastream -> src/lampastream, installer, systemd units, docs/LampaStream_*.md).
#   2. sed every tracked text file:  LampaStream -> LampaStream, lampastream -> lampastream,
#      LAMPASTREAM -> LAMPASTREAM.  Excluded: built web bundles (regenerated by `npm run build`),
#      docs/archive/** content (history), docs/LampaStream_rename_inventory.md, binaries.
#   3. Prints every remaining occurrence for review.
#
# What it does NOT do: the installer migration of a running install (that is the
# Claude Code task), `npm run build`, tests, commits.
#
# Run from the repo root on a clean tree:  bash scripts/rename-to-lampastream.sh
set -euo pipefail

if [[ ! -d .git ]]; then echo "run from the repository root"; exit 1; fi
if [[ -n "$(git status --porcelain --untracked-files=no)" ]]; then echo "tracked files have uncommitted changes — commit or stash first"; exit 1; fi

BRANCH=rename/lampastream
git checkout -q -b "$BRANCH" 2>/dev/null || git checkout -q "$BRANCH"
echo "on branch $BRANCH"

# ---------------------------------------------------------------- 1. paths
echo "== renaming paths"
# files first (deepest first), then directories, so git mv never sees a moved parent
git ls-files | grep -iE 'lampastream' | awk '{ print length, $0 }' | sort -rn | cut -d' ' -f2- | while read -r old; do
  new="${old//LampaStream/LampaStream}"; new="${new//lampastream/lampastream}"; new="${new//LAMPASTREAM/LAMPASTREAM}"
  # only rename the file's own name here; parent directory renames happen below
  odir=$(dirname "$old"); ndir=$(dirname "$new")
  if [[ "$odir" == "$ndir" ]]; then
    git mv "$old" "$new"; echo "  $old -> $new"
  fi
done
# directories (only src/lampastream today; handled generically)
for d in $(git ls-files | grep -iE '(^|/)lampastream/' | sed -E 's#(.*/)?lampastream/.*#\1lampastream#' | sort -u); do
  n="${d//lampastream/lampastream}"
  git mv "$d" "$n"; echo "  $d/ -> $n/"
done

# ---------------------------------------------------------------- 2. content
echo "== rewriting content"
EXCLUDE_RE='(^docs/archive/|^docs/LampaStream_rename_inventory\.md$|/webui/assets/|\.(png|jpg|jpeg|gif|ico|woff2?|ttf|pdf|bin|pyc)$)'
git ls-files -z | while IFS= read -r -d '' f; do
  [[ "$f" =~ $EXCLUDE_RE ]] && continue
  grep -qI . "$f" 2>/dev/null || continue            # skip binary
  grep -qE 'LampaStream|lampastream|LAMPASTREAM' "$f" || continue
  sed -i -e 's/LampaStream/LampaStream/g' -e 's/lampastream/lampastream/g' -e 's/LAMPASTREAM/LAMPASTREAM/g' "$f"
  echo "  $f"
done

# "formerly known as" note in the README, once
if ! grep -q "formerly LampaStream" README.md; then
  sed -i '0,/^# LampaStream/s//# LampaStream\n\n> Formerly known as **LampaStream**; renamed when the project outgrew Philips Hue./' README.md
fi

# ---------------------------------------------------------------- 3. report
echo
echo "== remaining occurrences (expected: archive history, the rename inventory, the README note)"
git grep -n -E 'LampaStream|lampastream|LAMPASTREAM' -- . ':!*/webui/assets/*' || echo "  (none)"
echo
echo "== summary"
git status --short | awk '{print $1}' | sort | uniq -c
echo
cat <<'NEXT'
Next, in this order:
  1. cd web && npm run build && cd ..          # regenerates the bundled assets under src/lampastream/webui
  2. pip install -e '.[dev]' && pytest -q      # imports and installer tests must be green
  3. cd web && npm test -- --maxWorkers=2 && cd ..
  4. git add -A && git commit -m "Rename LampaStream to LampaStream (mechanical)"
  5. Claude Code: implement the installer migration (docs/deployment-rename-cutover task) on this branch.
  6. Merge to master, then the one watched deploy on the LXC.
NEXT
