import { test, expect } from '@playwright/test'
import { setupPreview } from './preview-fixture'

test('Energy Trigger links open the requested Effect and Band Colours saves both editor modes', async ({ page }, info) => {
  const socket = await setupPreview(page)
  const base = { effect_type: 'band_colours', band_colours: ['#F42525', '#25F425', '#2525F4'], band_playback: 'static', band_advance: 'beat', band_advance_interval_s: 2 }
  let effects = [{ ...base, id: 'low', name: 'Quiet glow' }, { ...base, id: 'high', name: 'Bright bands' }]
  const energy = { id: 'e', name: 'Room trigger', energy_source: 'off', low_energy_effect_id: 'low', high_energy_effect_id: 'high' }
  await page.route('**/api/effects', route => route.fulfill({ json: effects }))
  await page.route('**/api/energy-profiles', route => route.fulfill({ json: [energy] }))
  await page.route('**/api/analysers', route => route.fulfill({ json: [{ id: 'a', name: 'Room analysis', lower_cutoff_freq: 20, higher_cutoff_freq: 20000 }] }))
  await page.route('**/api/effects/*', route => {
    const id = new URL(route.request().url()).pathname.split('/').pop()
    const body = route.request().postDataJSON()
    effects = effects.map(effect => effect.id === id ? { ...effect, ...body } : effect)
    return route.fulfill({ json: effects.find(effect => effect.id === id) })
  })
  await page.reload()
  const controls = page.getByTestId('live-energy-source')
  await expect(controls.getByText('Energy Trigger', { exact: true })).toBeVisible()
  await expect(controls.getByRole('link', { name: 'Quiet glow' })).toBeVisible()
  await expect(controls.getByTestId('low-energy-effect')).toHaveCSS('opacity', '0.4')
  socket().send(JSON.stringify({ type: 'frame', colour: { r: 0, g: 0, b: 0 }, last_energy_input: 1, mix: 1 - .9 ** 200 }))
  await expect(page.getByTestId('energy-blend').getByText('100%', { exact: true })).toBeVisible()
  await page.getByLabel('Editor mode').selectOption('expert')
  await expect(controls.getByRole('radio')).toHaveCount(5)
  await expect(controls.getByRole('radio', { name: 'Off', exact: true })).toHaveAttribute('aria-checked', 'true')
  await expect(controls.getByTestId('energy-parameters')).toHaveCount(0)
  await page.screenshot({ path: info.outputPath('energy-trigger-off.png'), fullPage: true })
  await controls.getByRole('link', { name: 'Quiet glow' }).click()
  await expect(page.getByTestId('editor-name-input')).toHaveValue('Quiet glow')
  const bands = page.getByRole('region', { name: 'Band colours', exact: true })
  await expect(bands.getByText('20–200 Hz', { exact: true })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Colour Table & Playback' })).toHaveCount(0)
  await bands.getByRole('group', { name: 'Band count' }).getByRole('button', { name: '5', exact: true }).click()
  await expect(bands.locator('input[type="color"]')).toHaveCount(5)
  await page.getByTestId('band-row-2').getByRole('button').click()
  await page.getByRole('button', { name: 'Use #FF9E3B', exact: true }).click()
  await expect(page.getByLabel('Band 3 colour', { exact: true })).toHaveValue('#ff9e3b')
  await page.screenshot({ path: info.outputPath('band-colours-standard.png'), fullPage: true })
  await page.getByTestId('mode-expert-btn').click()
  await page.getByRole('button', { name: 'Loop', exact: true }).click()
  await page.getByRole('button', { name: 'Every…', exact: true }).click()
  await page.getByRole('button', { name: 'Increase Interval (s)', exact: true }).click()
  await expect(page.getByRole('spinbutton', { name: 'Interval (s)', exact: true })).toHaveValue('2.1')
  await page.getByRole('region', { name: 'Colour Table & Playback' }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: info.outputPath('band-colours-expert.png'), fullPage: true })
  await page.getByTestId('editor-save').click()
  await expect(page.getByTestId('effects-gallery')).toBeVisible()
  expect(effects[0].band_colours).toHaveLength(5)
  expect(effects[0].band_colours[2]).toBe('#FF9E3B')
  expect(effects[0].band_playback).toBe('loop')
  expect(effects[0].band_advance_interval_s).toBe(2.1)
  await page.getByRole('button', { name: 'Now Playing', exact: true }).click()
  await page.getByRole('link', { name: 'Bright bands', exact: true }).click()
  await expect(page.getByTestId('editor-name-input')).toHaveValue('Bright bands')
  await page.getByTestId('effect-type-change').click()
  await page.getByTestId('type-option-band_colours_spatial').click()
  await page.getByTestId('editor-save').click()
  await expect(page.getByTestId('effects-gallery')).toBeVisible()
  expect(effects[1].effect_type).toBe('band_colours_spatial')
})
